### ISSUE TITLE
[CS 1.6] Underscore sign displays as white space

### ISSUE THREAD

**Issue by grz0** [ValveSoftware/halflife#104]
Underscore sign "_" displays as white space in console and player stats table.

**Comment by cl0ne** [comment]
@alfred-valve Any news?

**Comment by thedoorisstuck** [comment]
bumping, issue still persists.

**Comment by RauliTop** [comment]
@mikela-valve take a look here please. Should be fixed in Next release

**Comment by keks24** [comment]
This issue still persists:

**Operating system / Kernel version**
```bash
$ uname -a
Linux sharkoon 5.4.60-gentoo #1 SMP Sat Aug 29 16:02:28 CEST 2020 x86_64 Intel(R) Core(TM) i5-3450 CPU @ 3.10GHz GenuineIntel GNU/Linux
```

**Flatpak version**
```bash
$ flatpak --version
Flatpak 1.6.4
```

**Flatpak information**
```bash
$ flatpak info com.valvesoftware.Steam

Steam - Manage and play games distributed by Steam

          ID: com.valvesoftware.Steam
         Ref: app/com.valvesoftware.Steam/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.0.0.66
     License: LicenseRef-proprietary
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 39.6 MB
     Runtime: org.freedesktop.Platform/x86_64/20.08
         Sdk: org.freedesktop.Sdk/x86_64/20.08

      Commit: 9b925ba889e031e7c7f50d4853cdf74b2bc70808f68b402c7cbb2810f62b4bb1
      Parent: f536db0f8ac85ccee11b091d1e21df53fbdcd8291ac39704860512f4a37da228
     Subject: Switch to 20.08 final (7d7ed8b2)
        Date: 2020-08-31 19:15:42 +0000
```
```bash
$ flatpak info org.freedesktop.Platform

Freedesktop Platform - Shared libraries

          ID: org.freedesktop.Platform
         Ref: runtime/org.freedesktop.Platform/x86_64/20.08
        Arch: x86_64
      Branch: 20.08
     Version: 20.08.0
     License: GPL-2.0+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 731.6 MB

      Commit: 54fc005a60be576aead95993847430df346c11daf1740efabb8fde39638da84a
     Subject: Export org.freedesktop.Platform
        Date: 2020-08-31 16:51:12 +0000
```
```bash
$ flatpak info org.freedesktop.Platform.Compat.i386
          ID: org.freedesktop.Platform.Compat.i386
         Ref: runtime/org.freedesktop.Platform.Compat.i386/x86_64/20.08
        Arch: x86_64
      Branch: 20.08
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 388.3 MB

      Commit: 35bd3156b2831fd91b16113d85347f701439207542d87568e97ce4573518ac99
     Subject: Export org.freedesktop.Platform.Compat.i386
        Date: 2020-08-31 16:38:30 +0000
```
```bash
$ flatpak info org.freedesktop.Platform.GL32.default
          ID: org.freedesktop.Platform.GL32.default
         Ref: runtime/org.freedesktop.Platform.GL32.default/x86_64/20.08
        Arch: x86_64
      Branch: 20.08
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 120.9 MB

      Commit: 22db36cf1224ce811a23199a70b9ece4b34c44ea5d6bfa08eebe678fd3b00265
     Subject: Export org.freedesktop.Platform.GL.default
        Date: 2020-08-31 16:38:39 +0000
```
```bash
$ flatpak info org.freedesktop.Platform.GL.default
          ID: org.freedesktop.Platform.GL.default
         Ref: runtime/org.freedesktop.Platform.GL.default/x86_64/20.08
        Arch: x86_64
      Branch: 20.08
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 117.2 MB

      Commit: 13b663698f585858f14e30f70bbd07b07e3d4825617115e803acd4d4a2ed5795
     Subject: Export org.freedesktop.Platform.GL.default
        Date: 2020-08-31 16:36:20 +0000
```
```bash
$ flatpak info org.freedesktop.Platform.Locale
          ID: org.freedesktop.Platform.Locale
         Ref: runtime/org.freedesktop.Platform.Locale/x86_64/20.08
        Arch: x86_64
      Branch: 20.08
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 1.3 GB

      Commit: 02a02706089975568f19522dd02b2b04e68212fdf6ef6780c2baafabf9a60b02
     Subject: Export org.freedesktop.Platform.Locale
        Date: 2020-08-31 16:38:55 +0000
```
```bash
$ flatpak info org.freedesktop.Platform.openh264

openh264 - OpenH264 Video Codec provided by Cisco Systems, Inc.

          ID: org.freedesktop.Platform.openh264
         Ref: runtime/org.freedesktop.Platform.openh264/x86_64/2.0
        Arch: x86_64
      Branch: 2.0
     Version: 2.1.0
     License: LicenseRef-proprietary=https://www.openh264.org/BINARY_LICENSE.txt
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 778.2 kB

      Commit: 73f998362a6fc0d57e0c7e83e928d32b0ec14d10d0d94291033976bdcecc6b6b
      Parent: 15266352ca7587793d013fdb17530a24d728e09be4f4cf315dc5bf99ad4323e8
     Subject: Export org.freedesktop.Platform.openh264
        Date: 2020-06-18 15:48:18 +0000
```
```bash
$ flatpak info org.freedesktop.Platform.VAAPI.Intel
          ID: org.freedesktop.Platform.VAAPI.Intel
         Ref: runtime/org.freedesktop.Platform.VAAPI.Intel/x86_64/20.08
        Arch: x86_64
      Branch: 20.08
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 44.1 MB

      Commit: e21a5a785d1f04068a57705cf2444cf92178d27e1c08a543c6fbeaf8d2800eb2
     Subject: Export org.freedesktop.Platform.VAAPI.Intel
        Date: 2020-08-31 16:37:39 +0000
```

**Steam client version**
![20200908-001750_screenshot](https://user-images.githubusercontent.com/13721064/92418629-cdcedb00-f168-11ea-8b00-4b8cab8dc843.png)

**Counter-Strike version**
![20200908-001958_screenshot](https://user-images.githubusercontent.com/13721064/92418701-17b7c100-f169-11ea-8cc3-1cb1b0925a0f.png)

**Comment by Maxi605** [comment]
I can't reproduce this issue, works fine for me.

**Comment by AdamRichard21st** [comment]
Hi, guys,
I can reproduce this issue on my Pop Os 20.04 lts.
A custom `TrackerScheme.res` file + setting `"dropshadow" "1"` on `Scheme.Fonts.Default[1]` seems to fixes it tho.

**Comment by keks24** [comment]
Interesting. By adding `"dropshadow" "1"` the underscore indeed does appear, but in my case it has no shadow. :smile:

I would consider this as a workround, since the issue might be somewhere else.

![20200910-213855_screenshot](https://user-images.githubusercontent.com/13721064/92792770-204d0900-f3ae-11ea-8adb-d33a56f40592.png)

**Comment by keks24** [comment]
I got it working now. The following files have to be adapted:

In the menus: `/steamapps/common/Half-Life/cstrike/resource/TrackerScheme.res`:
```no-highlight
[...]
        //////////////////////// FONTS /////////////////////////////
        //
        // describes all the fonts
        Fonts
        {
                // fonts are used in order that they are listed
                // fonts listed later in the order will only be used if they fulfill a range not already filled
                // if a font fails to load then the subsequent fonts will replace
                "Default"
                {
                        "1"
                        {
                                "name"          "Tahoma"
                                "tall"          "16"
                                "weight"        "0"
                                // custom - 20200912 - rfischer: make underlines visible
                                "dropshadow" "1"
                        }
                }
[...]
```

![20200912152244_1](https://user-images.githubusercontent.com/13721064/92996480-2eb13700-f50c-11ea-8c8a-ca9d33de7b0c.jpg)

In-game: `/steamapps/common/Half-Life/cstrike/resource/ClientScheme.res`:
```no-highlight
        //////////////////////// FONTS /////////////////////////////
        //
        // describes all the fonts
        Fonts
        {
                // fonts are used in order that they are listed
                // fonts listed later in the order will only be used if they fulfill a range not already filled
                // if a font fails to load then the subsequent fonts will replace
                "Default"
                {
[...]
                        "2"
                        {
                                "name"          "Verdana"
                                "tall"          "13"
                                "weight"        "600"
                                "yres"  "600 767"
                                // custom - 20200912 - rfischer: make underlines visible
                                "dropshadow" "1"
                        }
[...]
```

![20200912151455_1](https://user-images.githubusercontent.com/13721064/92996407-b3e81c00-f50b-11ea-969b-0225909682d2.jpg)

**Comment by fysiks1** [comment]
Adding the dropshadow in TrackerScheme.res as suggested fixed the underscores in the console.  I don't think I had to edit ClientScheme.res to get the scoreboard showing them.  I've been living with this for so long or rarely encounter a player's name that I know had underscores that I can't remember if that has always worked in the scoreboard or not.

**Comment by keks24** [comment]
It seems, that displaying the underscore character is somehow connected with the in-game resolution. See [Edit - 20200924 - 2219](https://github.com/ValveSoftware/halflife/issues/104#issuecomment-691487622).
