### ISSUE TITLE
animation skip during m4/ak spray

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/halflife#1183]
Its been going on since updates that happend 2 weeks ago. when u are doing full on spray. 5-7+ bullets. i think in between animation skips or there is a lag. my ping to server is around 20 ms and i never had that problem.
i also came across this topic -> https://github.com/ValveSoftware/halflife/issues/1133 which i think was created around updates time as well. i myself know 2 more people dealing with same issue

**Comment by t40am** [comment]
So, I contacted Steam Support to explain them what is going on and this is what I received from them.
------------------------------------------------------------------------------------------------------------------------
Hello,

A staff member has replied to your question:

Hello --------.

Thank you for contacting Steam Support.

We apologize for the delay.

Thank you for your comments, we value feedback from the Steam community. I will forward your comments onto the appropriate department.

Additionally, if you wish to share an opinion, suggestion, or idea with the community as well, please visit the Suggestions/Ideas section of the Steam Forums, found here:

http://steamcommunity.com/discussions/forum/10/

This forum is regularly read by Valve's development team.
----------------------------------------------------------------------------------------------------------
Do you guys think that Valve are ever going to fix this? I know that the problem occurs not because of my internet connection or hardware but because of a glitch in CS's coding.

**Comment by sbolokanov** [comment]
That's hard to tell. Given how long it has been since it was introduced I doubt it.
Just week ago I've started playing again and I found out that the clunky recoil is still present with bullets acting strangely, which in turn makes it hard to play (I would say impossible). Guess I will have to wait for this to get fixed (if ever).

Just to point out, yes I've been playing with both "stable" and beta.

**Comment by WPMGPRoSToTeMa** [comment]
@sbolokanov you should play on 6153 beta server, not on beta client.

**Comment by t40am** [comment]
I have included a link to this thread and a video where the problem is shown in my message to Steam Support. Hopefully my message will not be ignored.

**Comment by sbolokanov** [comment]
@WPMGPRoSToTeMa there are no servers that use beta - ever . They don't even use recent versions to begin with... Btw I don't see why would that be a server issue either. With cracked versions of CS (read old) on same servers, there is no recoil problem.

If you have links or something as to why/what has changed, I do gladly read them.

**Comment by t40am** [comment]
So, I got a message from Steam Support again. They said that they are going to investigate this problem and take appropriate actions.

**Comment by t40am** [comment]
6153 servers work fine, any version below makes guns shoot laggy bullets. A majority of servers use outdated versions, server admins are not experiencing this bug and they are not going to update their servers anyway.

**Comment by t40am** [comment]
The solution to this problem would be really simple - force HLDS users to update their servers. Of course normal gamers can't do anything about this unless Valve decides to take action. 
Sorry for triple posting by the way. It's just that not many people look in to this anymore. My friend has this problem as well and he thought it was his computer and internet that's causing it. That's how most of the people think right now.

**Comment by makefury** [comment]
@t40am 

It appears they've already pushed 6153 to the normal branch, both the beta and standard are 6153 now.

**Comment by t40am** [comment]
3 weeks ago I asked my server provider to update their servers, they did and it was still version 6132 (the one that still has the bug). Then I asked if I they could update their servers to latest beta version (the one that fixes the bug) but they refused because it's not stable and has some in-game issues.

**Comment by DeN4gg** [comment]
I've been following this thread for so long and tried almost all the solutions were provided. 

Lately I found what I think it's a solution or at least a partial fix for me.

Below are the commands which you have to run on a Command Prompt window with Administrator rights:

bcdedit /set disabledynamicktick yes
bcdedit /set useplatformclock true

and restart.

I wish you all Merry Christmas.

**Comment by WPMGPRoSToTeMa** [comment]
@DeN4gg there is already a solution, you need to upgrade your server to 6153 beta.

**Comment by DeN4gg** [comment]
@WPMGPRoSToTeMa thx bro <3

**Comment by DeN4gg** [comment]
6153 beta. no fix my problem (

**Comment by TjaardA** [comment]
this fixed it for me !!!!!!

/etc/sysctl.conf    (Debian) 

##########################################################################
#### TjaardA # TjaardA # TjaardA # TjaardA # TjaardA # TjaardA # TjaardA # TjaardA  ####
##########################################################################

#  increase TCP default/max buffer size.
#    (def.212992) 
net.core.rmem_default = 212992 
net.core.rmem_max = 212992
net.core.wmem_default = 212992 
net.core.wmem_max = 212992

#  maximum total buffer-space allocatable in units of pages 4096 bytes.
#  (def. 188283 251047 376566)
net.ipv4.tcp_mem = 81920 106496 131072
net.ipv4.udp_mem = 81920 106496 131072

#  increase Linux autotuning TCP buffer limits .
# (def.rmem 4096 87380 6291456) (def.wmem 4096 16384 4194304) 
net.ipv4.tcp_rmem = 8192 86016 4194304
net.ipv4.tcp_wmem = 8192 86016 4194304

#  If your servers talk UDP, also up these limits.
#  (def.4096)
net.ipv4.udp_rmem_min = 8192
net.ipv4.udp_wmem_min = 8192

# Disable Nagle's Algorithm.
net.ipv4.tcp_autocorking = 0 

# Adjust Network/Application Factor.
net.ipv4.tcp_adv_win_scale = 5

##########################################################################
#### TjaardA # TjaardA # TjaardA # TjaardA # TjaardA # TjaardA # TjaardA # TjaardA  ####
##########################################################################

**Comment by erdemtekin** [comment]
@alfred-valve I bought Counter-Strike on Steam a few months ago.I play this on steam.My ping is 0-10 But when I jump,duck and shoot I can see LAG.I can't play this smooth.Half-Life hasn't this problem.Condition Zero and Counter-Strike have this problem.

Here is video:
https://www.youtube.com/watch?v=3z3Cy4Ciexo

I am big fan of Counter-Strike.Please fix it...

**Comment by Maxpain177** [comment]
@erdemtekin 
sv_maxupdaterate 102
sv_maxrate 100000
sys_ticrate 1060

**Comment by erdemtekin** [comment]
@Maxpain177 Hey man thanks for reply but  it doesn't fix.I tried everything(rate codes,disable firewall,compatibility modes,disable DEP,formatting Windows etc.).İt is bug :(

**Comment by sbolokanov** [comment]
@erdemtekin Same here. It's old issue. Don't expect it to be fixed!

**Comment by di57inct** [comment]
@sbolokanov "Don't expect it to be fixed!"
I think we've successfully found Valve the most suitable slogan.

**Comment by ViBENo1** [comment]
@di57inct lol you're right :D

**Comment by erdemtekin** [comment]
@alfred-valve 
Hey Valve! 
Why do not your customers happy? 
Have you ever thought? 
I will tell you 
Because You're not interested
And you aren't helping

**Comment by WPMGPRoSToTeMa** [comment]
@erdemtekin cl_lw 0 is absolutely legal.

**Comment by erdemtekin** [comment]
@WPMGPRoSToTeMa cl_lw 0 wasn't allowed in ESL

**Comment by TjaardA** [comment]
fixed go test 212.83.131.212:27015 EliTe-CommuniTy #1 | DD2 Only | 1000FPS |

**Comment by w4Ld1** [comment]
i have this issue since 2009, someone idea how to get back the money of all valve games? 
or maybe fix? 
45min gameplay = red dots in net_graph

i tried really everything on earth

**Comment by erdemtekin** [comment]
Worst game in the world for me.Because I spent many hours to fix it.

**Comment by fe0** [comment]
No more online gaming? Play Cs:Go? Fix this bug!

**Comment by erdemtekin** [comment]
@fe0 Counter Strike 1.6 was my life.(When I use WinXP and old build)
Now, I don't play valve games anymore...
Because I can't play lagless
Because,I cant play it smoothly on 60hz notebook screen
Because,I can't spent hours to fix it anymore
Because I hate Valve and Valve games

**Comment by djdallmann** [comment]
when fps_max is equal to or greater (>=) 91, animations skip occurs on higher latency servers 60-70ms, with fps_max 92 i only get 3 decals on a full m4a1 spray consistently but the crosshair is moving as if bullets are coming out.  try fps_max 90 or below to see if it fixes your issues.

**Comment by erdemtekin** [comment]
@djdallmann 

"cl_lw 0" fixes my problem but it isn't legal in tournaments and matches

I know it is a client problem.I can play smoothly in singleplayer (with bots)

I tried rate commands,disabling firewall,disabling DEP etc. but they didn't fix problem

Also,I am using vsync.When I set fps to 100, it doesn't fix problem.So,I must play in 60fps because I am using 60hz screen.

Here is my gameplay video:
Note:if you watch in fullscreen and 720p you can see lag.(When I jump and fire)
https://www.youtube.com/watch?v=3z3Cy4Ciexo

**Comment by erdemtekin** [comment]
WTF! He is saying "Problem Fixed" now! It related to you.Valve still didn't fix Counter Strike and Condition Zero 

Here is his video:
https://www.youtube.com/watch?v=6RxPCoQY570

**Comment by hadig** [comment]
its 2017 and still not fixed, good job alfredo_volvo

**Comment by Maxpain177** [comment]
@hadig LOL

**Comment by Kosta4934** [comment]
Cause of this bug i started to hate 1.6 :( Not just htis bug, recoil bug, movement bug, bhop bug.

**Comment by djdallmann** [comment]
This is a still an issue, client side animations are broken online. The bullets are counting down in the bottom right corner when you spray automatic rifle (m4a1, ak47 etc) but the visual decals on the wall, mussle flash and sounds aren't all there; it skips.

**Comment by djdallmann** [comment]
I bought a linux server in New York to do testing on, it is running around 900 fps constant and the usual max/min rates 101, 30000k. I've came to the conclusion that it is routing/latency the server that is causing the spray lag issues and is also likely related to the update referenced in my last post in which hlds is no longer forcing recoil synchronization between server to client, so now it appears to heavily rely on super stable routing/connection to the internet server which can be fragile and out of most players control.

- On lan I do not have these issues, when routing and latency is inconsistent to my server I get these spray lag issues. 
- I have a decent connection 10down 5up which is more than enough for CS 1.6, my network is isolated and has dedicated bandwidth.
- Changing client, computer, network adapter and server settings does not resolve spray skip settings adequately, it still skips with poor routing with inconsistent latency.

Hope this helps anyone and for the most part it might be out of your hands since it relies on internet routing (ISP and other providers). Just find a different server to play on :(

**Comment by WPMGPRoSToTeMa** [comment]
@djdallmann did you try 6153 beta?

**Comment by djdallmann** [comment]
Been a while since I tried, I recall previous posts saying 6153 beta is the same as base but it was never confirmed by @alfred-valve

**Comment by WPMGPRoSToTeMa** [comment]
@djdallmann what is the size of `cs.so`?

**Comment by djdallmann** [comment]
md5sum ./hlds/cstrike/dlls/cs.so
d0758a1115c7d7ef4f0d2ff61309b6db  ./hlds/cstrike/dlls/cs.so

**Comment by WPMGPRoSToTeMa** [comment]
@djdallmann it is non-beta.

**Comment by djdallmann** [comment]
I'll try full server install using -beta beta and see if it changes anything

**Comment by djdallmann** [comment]
I was able to update to beta, there's some weird bugs with steamcmd. Had to blow away steam folder config and then fresh install, i'm now getting this for cs.so. Hoping this beta helps.
md5sum cs.so
861c456d5003bd1a248d14e479e7f6c1  cs.so

**Comment by djdallmann** [comment]
Wow recoil is amazing (normal) on BETA

**Comment by WPMGPRoSToTeMa** [comment]
> md5sum cs.so
861c456d5003bd1a248d14e479e7f6c1 cs.so

Yup, it is beta.

**Comment by Everlastingbulletlag** [comment]
Hi all I got this recoil lag since 2004 in all Steam games. Even in csgo. I have tried all possible solutions. Also buying new pc's and now I see this post. Do you have a solution to fix this? I dont have a server.  Im not that into solving pc. problems, so can you tell me very 'easy way' how to solve it? I have told Valve so many times about this problem and they just doing nothing about this bug, so a month ago I stopped playing any steam games. But I hope you can help me? Is it a server bug problem or what? In that case I understand why I cant solve it. Many players have this now and dont waste money in buying new pc's - Steam accounts cos I wont help you. 

I know how you all suffer from this bug. I would love to play again. But cant fix this😭

**Comment by Everlastingbulletlag** [comment]
@alfred-valve

Can you plz help us solving this recoil lag. I have the lag in so many years I love your games alot but its unplayable with this lag and alot of treads and videos on youtube about the bug. I hope so much you can try to get Valve to fix it=) If you can help with this you will make so many players happy. I understand its a very hard problem since I tried everything possible. But I hope so much for a fix.

**Comment by djdallmann** [comment]
The 2013 bullet skip issue is solved by the server running the beta version of hlds which is out of the control of most players.

**Comment by SuparyeN** [comment]
Still no fix for windows...

**Comment by Everlastingbulletlag** [comment]
djdallmann I tryed your fix but recoil and movement lag is still there. I dont know what to do. I dont play very often anymore cos all my steam games are with this lag also bulletlag. I really dont get why this aint fixed yet😥😭

**Comment by w4Ld1** [comment]
Everlastingbulletlag what Steam Support says?

**Comment by Everlastingbulletlag** [comment]
W4Ld1

They told me that the reason could be missing entrys in game files. And that I should go to regedit and call a entry steamapps.old as I remember I can find exactly what I did cos I saved the post so if you want? I can post what they said. 
but I tryede it but the lag was shortly gone but came back.

But I did buy a new account same time so can also because of that the game shortly was smooth but I buyed one more resently and the lag was there all the time, so buying new accounts dont solve anything. But if some of you buy new accounts try to buy it with a new email not the old one. Cos I havent tryed that but I dont think i do anything but I heard someone mentioned that it maby would be different.

I have tryed almost everything to solve this also buying new very powerfull pc and the lag is still there so thats why I maby thung its something with the steam files cos the lag is less first time you install steam. Its like something is change when you load cs second time.

**Comment by erdemtekin** [comment]
@alfred-valve 
## Game has been updated but valve still did not fix this problem
also here is my gameplay compare videos: (_default rate settings_ VS _new rate settings_)

**Gameplay with default rate settings**: https://www.youtube.com/watch?v=3z3Cy4Ciexo
 (everything is default)

**Gameplay with new rate settings**: https://www.youtube.com/watch?v=XEMZZ0u8YY0

and yes i guess gameplay is better on new rate setiings

**Comment by exegg** [comment]
I never had this issue before. Now it's been happening to me since a week ago or so, in a few servers. It's so annoying... I can see CS updated recently since my version states

Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
Exe build: 09:10:05 Jul  7 2017 (7561)

**Comment by WPMGPRoSToTeMa** [comment]
@exegg alfred returned bug from 6153 to 7561. (while it was fixed in 6153 beta)

**Comment by TjaardA** [comment]
Hi Github, 

let me explain again.

- The year 1999 HL got online all servers did not even have 1 Gig or RAM.
  Linux and windows use a partial RAM for networking and all worked fine.

- Now servers are a lot larger and carry more RAM memory.
  This results into larger Network Buffers and data flow issues.
  
This is why you all experiance shooting lag and animation skip issues.
check the settings i posted above, these settings also can be changes at windows servers.

Note:  this can only be done server side.

Greetz TjaardA

**Comment by djdallmann** [comment]
It's fixed in hlds beta server build.

**Comment by SuparyeN** [comment]
@djdallmann Can you or anyone else test it on windows? The beta 6153 didn't fix it for me.

**Comment by erdemtekin** [comment]
Default client and server rates are too bad. Valveshit still ignores this issue.

**Comment by CSerL33T** [comment]
100% not fixed for Windows. Just try spraying with M249 it's horrible! Also noticeable with AUG while on zoomed and FAMAS on burst mode. It's so sad how it turned out like this now... it wasn't like this before.

**HLDS version**:
Protocol version 48
Exe version 1.1.2.7 (cstrike)
Exe build: 19:52:53 Aug  3 2020 (8684)

**Client version**:
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
Exe build: 19:53:27 Aug  3 2020 (8684)

**Comment by sp3c-dod** [comment]
this same issue also occurs in DOD 1.3 with the pistols, BAR, and STG
