### ISSUE TITLE
Loading a saved game where the active weapon has partially empty clip prevents reload

### ISSUE THREAD

**Issue by SamVanheer** [ValveSoftware/halflife#1707]
If you load a saved game where the active weapon has a partially empty clip, you cannot reload the weapon. Changing to another weapon and then back again, or picking up ammo fixes this.

To fix this bug in code, go to this line: https://github.com/ValveSoftware/halflife/blob/master/dlls/player.cpp#L3057

Add a call to TabulateAmmo right after this. It will resync ammo data and ensure it works correctly. Alternatively, update the weapons to use CBasePlayer::m_rgAmmo instead. Provided the client synchronizes them correctly, it should work just as well.

**Comment by tschumann** [comment]
Nice find - you should create a pull request for this too.

**Comment by mikela-valve** [comment]
Hi @SamVanheer, this should be fixed in the current HL1/OpFor betas.

**Comment by SamVanheer** [comment]
yup, looks like it's working.

**Comment by hobokenn** [comment]
still not working for some op4/bshift guns.
op4: revolver, deagle, smg, crossbow, sniper rifle.
bs: glock, revolver, smg, crossbow.

**Comment by mikela-valve** [comment]
Thanks @hobokenn. BS didn't get a beta update this round to reduce the number of test versions, it should be fixed when this fix is pushed to public. If you're seeing this in OpFor it probably has its own version of this bug, so I'll take a look at that.

**Comment by mikela-valve** [comment]
Fixed in the remaining titles. Will be in the next beta release.

**Comment by mikela-valve** [comment]
Fixed in 'Exe build: 11:11:14 May 21 2019 (8244)'.

**Comment by mikela-valve** [comment]
Closing as fixed.
