### ISSUE TITLE
[GoldSrc] Malformed strings can crash the game

### ISSUE THREAD

**Issue by magister4813** [ValveSoftware/halflife#2150]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/49805165/56455240-8887ee80-6364-11e9-8e31-d773dc69b8ec.gif)

The crash occurs when **wcsncpy** is called with the third argument negative inside the function **CHudSayText::SayTextPrint**.

![Screenshot_2](https://user-images.githubusercontent.com/49805165/56455071-b10ee900-6362-11e9-9d6a-d5a91f7282fa.png)

**Comment by mikela-valve** [comment]
Fixed, this will be included in the next beta update.

**Comment by mikela-valve** [comment]
Fixed in 'Exe build: 11:11:14 May 21 2019 (8244)'.

**Comment by Splatt581** [comment]
The bug still works on last beta. To verify this, you need to connect to HLTV server and send a few labels to chat, for example `say #spec_help_text #spec_help_text`

**Comment by mikela-valve** [comment]
Oh, I'm sorry, I completely misinterpreted this report. I thought it was reporting that the third parameter to SayTextPrint (clientIndex) was negative and that was causing a crash (which I found it would if it is negative, so that is what I fixed). I should have the actual issue here fixed in the next beta.

**Comment by mikela-valve** [comment]
This should be properly fixed now in beta 'Exe build: 16:32:50 May 22 2019 (8245)'.

**Comment by Splatt581** [comment]
I confirm, fixed.

**Comment by magister4813** [comment]
Thank you! Glad I can help this game.

**Comment by mikela-valve** [comment]
Closing as fixed.
