### ISSUE TITLE
[CS 1.6] When downloading maps with fastdownload, files without path in the *.res file are created as folders in cstrike_download.

### ISSUE THREAD

**Issue by Krapfenmann** [ValveSoftware/halflife#234]
When downloading a custom map with valid *.res file, the Game will only download files with a path named in the *.res file of the map. 

For example:

*.wad files are mostly stored at the standart game location ("cstrike"). This is a part of the res file for the custom map: de_plaka:

---

// res file - de_plaka
de_plaka.wad
decals.wad
gfx/env/plakaup.tga
gfx/env/plakadn.tga
gfx/env/plakalf.tga
gfx/env/plakart.tga
gfx/env/plakaft.tga
gfx/env/plakabk.tga
models/de_plaka/plaka_pillar.mdl
models/de_plaka/plaka_tree1.mdl

---

Then a folder with the name "de_plaka.wad" will be created instead of the true *.wad file. This folder is empty. So the map will NOT be playable for the client because of the missing texture file and the game crashes!

This also works with other files like *.txt as long as it does not have a path!

Here you can see that:
![cstrike_downloads_fastdl_creates_folders](https://f.cloud.github.com/assets/3612995/164029/60466654-786f-11e2-833f-ca3f65a02db4.jpg)

Tried to write it like this:

/de_plaka.wad

,into the *.res file but it also did not work. Then nothing will be created, no file, no folder.

Someone on the AMXmod forums confirmed that and had the same problem.

**Comment by XanderGS** [comment]
Seems this issue is back in the new steam updates.

**Comment by darcadarca** [comment]
I got the same problem with wad. I read all others topics about that from here but nothing to fix. In May, i have released a map without problems .. but now i get that error and without manual copy the .wad in cstrike.. other players will get crash.
Please fix that.. or mapping for 1.6 will drop low..
@ srry for poor engish.

**Comment by MyLittleRobo** [comment]
Still same issue. Using hlds downloaded via steamcmd.

**Comment by miguelk5** [comment]
Quick fix for this issue !
Since defintly this bug still happening  , but just with some map that includes .wad files like as_tundra. The fix is just use fast download feature :

cstrike / server.cfg 

add : sv_downloadurl "http://yourwebsite/my_cstrike/"

Then , create such directory on the root of your webspace .

Add there each .wad file that any map could need , important respect folder structure , example (sounds/monster.wav   , overview/map.bmp)   

Also i copied all needed files inside  a folder called "my_cstrike/cstrike_downloads"  because the steam version of CS1.6 download files inside cstrike_downloads folder
