### ISSUE TITLE
liblist.gam reference to hl.dll not parsing properly (mods are broken)

### ISSUE THREAD

**Issue by DonAKAUnq** [ValveSoftware/halflife#2725]
This started with the recent HL update (Oct. 8th).  Many mods don't have a custom dll so they refer to hl.dll by use of the line
``gamedll "..\valve\dlls\hl.dll"``

These mods are now crashing to desktop when starting a map.  The console gives the response
``Skipping library with illegal characters in path: ..\valve\dlls\hl.dll``
with a lot of svc_bad messages following.

Example mod where this happens: USS Darkstar.

**Comment by afwn90cj93201nixr2e1re** [comment]
Also maybe we should revert last update till not fixed? Coz there one issue with crashing on server enter, and one about crashing on serverbrowser, and they r reproducible now on stable, you can read comments on update page.

**Comment by LucesEnBabel** [comment]
Replacing the gamedll line with 
```
gamedll "dlls\hl.dll"
gamedll_linux "dlls/hl.so"
gamedll_osx "dlls/hl.dylib"
```
fixes the problem. The game runs in Linux and on Windows (Proton).

**Comment by JoelTroch** [comment]
@LucesEnBabel Did you had to copy the `valve/dlls/hl.$LIBEXT` and/or `valve/cl_dlls/client.$LIBEXT` inside the mod's directory for your workaround to work?

**Comment by LucesEnBabel** [comment]
No more workarounds were needed.

--
Sent from myMail for Android

Thursday, 10 October 2019, 02:19AM -03:00 from Joël Troch notifications@github.com<mailto:notifications@github.com>:


@LucesEnBabel<https://github.com/LucesEnBabel> Did you had to copy the valve/dlls/hl.$LIBEXT and/or valve/cl_dlls/client.$LIBEXT inside the mod's directory for your workaround to work?

**Comment by BlackShadow** [comment]
Tested They Hunger which is using custom .dll (einar.dll) and works perfectly fine.

**Comment by BlackShadow** [comment]
Tested They Hunger which is using custom .dll (einar.dll) and works perfectly fine.

Side Note: USS Darkstar also works fine with Steamfix (Steamfixes are community based fix). You need to apply  Steamfix to every old Goldsource mod or else mods may won't work. And it doesn't have anything with latest update. It was always like this. Older mods cannot function properly without Steamfix. Some Steamfix patches replaces liblist.gam only, some of them are has client.dll. Some mods need to edit their client.dll to make it work on Steam version. For USS Darkstar's side it can be easily fixed by editing liblist.gam. In short, no mods aren't broken.

**Comment by LucesEnBabel** [comment]
> USS Darkstar also works fine with Steamfix (Steamfixes are community based fix). You need to apply Steamfix to every old Goldsource mod or else mods may won't work. And it doesn't have anything with latest update. It was always like this. Older mods cannot function properly without Steamfix. Some Steamfix patches replaces liblist.gam only, some of them are has client.dll. Some mods need to edit their client.dll to make it work on Steam version. For USS Darkstar's side it can be easily fixed by editing liblist.gam. In short, no mods aren't broken.

Probably a bit off-topic: but most WON mods worked in the Steam version without the need for a fix (that in a nutshell give menu, icons, background and singleplayer support to the games). The only exception to this case was probably Half-Life: Invasion IIRC.

This issue is referencing the patch applied for https://github.com/ValveSoftware/halflife/issues/2221 that broke support for games that were referencing Half-Life's gamedll by using `..` to go up the root directory that were broken in the latest update.

**Comment by BlackShadow** [comment]
> Probably a bit off-topic: but most WON mods worked in the Steam version without the need for a fix (that in a nutshell give them menu, icons, background and singleplayer support to the games). The only exception to this case was probably Half-Life: Invasion IIRC.

Most of the older mods without works without Steamfix indeed, but these are mostly basic mods. Steamfix doesn't provide splash, background only. They also provide a modified client.dll (depending on the mod) and liblist.gam. Azure Sheep, Sweet Half-Life, They Hunger (Not Triology), as you mentioned Half-Life Invasion always gave me issues without Steamfix, because their Steamfix includes a custom client.dll not only liblist.gam

About the #2221 This may be the issue but im still defending the fact that no older mod should be played without Steamfix and literally every mod i've tried so far has it.

**Comment by BlackShadow** [comment]
> Probably a bit off-topic: but most WON mods worked in the Steam version without the need for a fix (that in a nutshell give them menu, icons, background and singleplayer support to the games). The only exception to this case was probably Half-Life: Invasion IIRC.

Most of the older mods works without Steamfix indeed, but these are mostly basic mods. Steamfix doesn't provide splash, background only. They also provide a modified client.dll (depending on the mod) and liblist.gam. Azure Sheep, Sweet Half-Life, They Hunger (Not Triology), as you mentioned Half-Life Invasion always gave me issues without Steamfix, because their Steamfix includes a custom client.dll not only liblist.gam

About the #2221 This may be the issue but im still defending the fact that no older mod should be played without Steamfix and literally every mod i've tried so far has it.

**Comment by DonAKAUnq** [comment]
> About the #2221 This may be the issue but im still defending the fact that no older mod should be played without Steamfix and literally every mod i've tried so far has it.

You're right, that may be the issue.  But I've played HL mods forever and have never used Steamfix for anything.  Yeah, some old mods you don't get the splash screen, but they worked without having to fix something.  Which by definition means something has broken.

**Comment by CS-PRO1** [comment]
@mikela-valve Please look at this, Critical fix is needed since many mods aren't working now.

**Comment by mikela-valve** [comment]
@DonAKAUnq @CS-PRO1 Could either of you give the beta update I just released a try? I made a limited change to the gamedll path checks added in #2221 that should allow mods with paths like those posted to work successfully.

The version in the console in-game did not change from the current release version but the BuildID shown in the Local Files section of the game properties should be `4280512` for this beta.

Thanks!

**Comment by DonAKAUnq** [comment]
@mikela-valve Just checked with the new beta, but the same problem is there.  Still getting the `
Skipping library with illegal characters in path: ..\valve\dlls\hl.dll` message in console.

**Comment by mikela-valve** [comment]
Sorry about that, somehow that beta version didn't have the latest changes in it. I just updated it again and tested it with that path. It should be BuildID `4280961`.

**Comment by DonAKAUnq** [comment]
@mikela-valve Yes that did it.  Confirming that BuildID 4280961 fixes this issue.

Thank you!

**Comment by CS-PRO1** [comment]
@mikela-valve  I can confirm the fix too. I hope this will be pushed in a critical hotfix as soon as possible (if it's not out already..)

**Comment by Caltwentynine** [comment]
@mikela-valve Just confirmed here as well, demo playback works too.

**Comment by mikela-valve** [comment]
Thanks all! Closing as fixed.

**Comment by seisdr** [comment]
Would you like to give me hl.so file,
