### ISSUE TITLE
25th Anniversary Update: Overbright not working

### ISSUE THREAD

**Issue by 54ac** [ValveSoftware/halflife#3424]
The Anniversary Update website states:

> Lighting fixes including the long-lost GL Overbright support!

However, toggling gl_overbright does not seem to make any difference, as can be seen in the following screenshots of the first lamp on the left on t0a0:

![HalfLife00](https://github.com/ValveSoftware/halflife/assets/6372741/73f8c305-d84b-45a5-bd47-7a3bc965eb9e)
![HalfLife01](https://github.com/ValveSoftware/halflife/assets/6372741/745064cc-eb6d-4108-966f-b1ba4195690a)

Compare this to the previous build with hw.dll patched to allow for overbright support:

![t0a00000](https://github.com/ValveSoftware/halflife/assets/6372741/b02d3d26-8363-4d60-baf7-9d08f4525282)
![t0a00001](https://github.com/ValveSoftware/halflife/assets/6372741/e35fc338-0118-4eb5-b217-696fcb6b62b7)

**Comment by Deus-nsf** [comment]
Ah I thought I was going crazy, yep gl_overbright 1 currently does nothing for me too, but beware, as even with the patched dll, lighting won't be 1:1 match with Software, environments will be, but not entities that will still look better lit in Software, I'm curious if Valve will be interested in fixing that too. I had screenshots at some point to show the subtle differences but I lost them, I'm sorry...

**Comment by megakarlach** [comment]
According to the screenshot you posted, the only thing they had fixed is the weird chromatic aberration effect was fixed. It still lacks the bloom from the actual overbright mode through.

**Comment by ficool2** [comment]
In OpenGL, `gl_overbright` is no longer used. The new command is `gl_use_shaders` (default 1), the overbright fix is implemented on the shader level

**Comment by Deus-nsf** [comment]
> In OpenGL, `gl_overbright` is no longer used. The new command is `gl_use_shaders` (default 1), the overbright fix is implemented on the shader level

Well, it's not working as intended then, because I compared on and off, and while there is indeed a difference, the overbright hack as well as software mode both have much metter lighting still.

**Comment by megakarlach** [comment]
> In OpenGL, `gl_overbright` is no longer used. The new command is `gl_use_shaders` (default 1), the overbright fix is implemented on the shader level

Disabling `gl_use_shaders` seems to making it much brighter.

**Comment by 54ac** [comment]
> In OpenGL, `gl_overbright` is no longer used. The new command is `gl_use_shaders` (default 1), the overbright fix is implemented on the shader level

The implementation seems to make the game a lot darker. It also doesn't seem to support multitexturing, at least on that particular wall. See here (gl_use_shaders 0 is brighter):

![HalfLife00](https://github.com/ValveSoftware/halflife/assets/6372741/56abc44d-5b43-4b22-95ee-af0611c07d2a)
![HalfLife01](https://github.com/ValveSoftware/halflife/assets/6372741/451b6077-3998-4996-9693-64e10f62b92c)

**Comment by 54ac** [comment]
Looks like the overbright check is still included in the latest hw.dll. Bypassing it enables gl_overbright like in the previous builds, allowing for more comparisons:

`gl_use_shaders 0`, `gl_overbright 0`:
![HalfLife00](https://github.com/ValveSoftware/halflife/assets/6372741/a1fb7505-f38c-477a-b06b-0498e583b579)

`gl_overbright 1`:
![HalfLife02](https://github.com/ValveSoftware/halflife/assets/6372741/15353101-aaaa-4940-9b90-18f8179489bd)

`gl_use_shaders 1`:
![HalfLife03](https://github.com/ValveSoftware/halflife/assets/6372741/4b728d33-1e52-4f67-a902-9ea2088f6f97)

**Comment by Deus-nsf** [comment]
Will doing the hex edit put you at a risk of getting VAC banned on multiplayer though? Heard that at some point, which is why I kind of prefer waiting for an official fix!

**Comment by 54ac** [comment]
> Will doing the hex edit put you at a risk of getting VAC banned on multiplayer though? Heard that at some point, which is why I kind of prefer waiting for an official fix!

I would assume so, just to be safe. But it's useful for comparisons, as seen above.

**Comment by Deus-nsf** [comment]
how do you hex edit the new dll though? the sector isn't the same, and the hex string is different too!

**Comment by 54ac** [comment]
> how do you hex edit the new dll though? the sector isn't the same, and the hex string is different too!

It's the same thing still, but at a different location:
![hl exe_-_PID_14572_-_Module_hw dll_-_Thread_15972__2023-11-18_17-02-58](https://github.com/ValveSoftware/halflife/assets/6372741/5dc731b9-6359-423d-980b-ef5e77c16881)

The jump instruction is now at offset 2378047 in hw.dll. I think the latest release of HLFixes linked above supports the latest build and enables gl_overbright without the need for manual hex editing, though in a different way, by forcing gl_texsort.

**Comment by Enokilis** [comment]
The new update doesn't appear to actually add overbrightness, but merely restores the original look of gl_overbright 0.
This is still a step in the right direction, as many lights are no longer clipped at the expense of the artist's intention. One consequence is that modern map compilers expect this quirky behavior and try to compensate for it, so now they will look wrong.

**Comment by SirYodaJedi** [comment]
> One consequence is that modern map compilers expect this quirky behavior and try to compensate for it, so now they will look wrong.

They'll look different, but not incorrect. When displayed with proper overbrightness, they'll just be slightly brighter, but not by much. The clamping only occurred above a certain brightness threshold (about 160, I think? the lightmaps are 24-bit); anything darker than that was basically the same.

To any map makers reading: add the `-limiter 255` argument to your HLRAD compilation step to remove the compensation done by VHLT.

**Comment by Matthaiks** [comment]
gl_use_shaders 0 vs gl_use_shaders 1
![XX](https://github.com/ValveSoftware/halflife/assets/3577122/5c28d445-d713-45f2-87e9-c34c09e67e5c)

IMHO, gl_use_shaders 1 looks pretty good.

**Comment by Enokilis** [comment]
Odd. I took this screenshot yesterday, and it definitely doesn't seem as bright.
![image](https://github.com/ValveSoftware/halflife/assets/29983795/50661255-8b77-4f98-ab54-f8779f232a0e)

Booting it up now, though, it does actually look brighter. Did they hotfix it, or was my config screwed?

**Comment by 54ac** [comment]
Seems like it got hotfixed today.

Looks fine now:
![HalfLife00](https://github.com/ValveSoftware/halflife/assets/6372741/676cb2a9-58ea-4641-89fa-8e27d4942876)
![HalfLife01](https://github.com/ValveSoftware/halflife/assets/6372741/83b7d702-3103-46fb-8eed-98c145a695f8)

The wall texture still changes for some reason, but the effect has indeed been fixed.

**Comment by jakura-nuva** [comment]
> Seems like it got hotfixed today.
> 
> Looks fine now: ![HalfLife00](https://user-images.githubusercontent.com/6372741/284028842-676cb2a9-58ea-4641-89fa-8e27d4942876.png) ![HalfLife01](https://user-images.githubusercontent.com/6372741/284028846-83b7d702-3103-46fb-8eed-98c145a695f8.png)
> 
> The wall texture still changes for some reason, but the effect has indeed been fixed.

And this is with gl_use_shaders "1"? The gl_overbright command is still defunct?

**Comment by 54ac** [comment]
> And this is with gl_use_shaders "1"? The gl_overbright command is still defunct?

Yes, this is `gl_use_shaders` 0 and 1 from the latest untouched build, so without the overbright patch. It seems that an update was pushed earlier today which modified hw.dll among other files, so it checks out.

**Comment by Enokilis** [comment]
> They'll look different, but not incorrect.
In comparison to stock maps, that is. They looked "fine" before since the clamping level was consistent across all maps, but now you won't ever get full brightness until you shine a flashlight onto something. I'll definitely be noticing sand textures out in the sun somehow not blooming out when they should.

**Comment by goodusername123** [comment]
## It seems like overbright/shaders/`gl_use_shaders` breaks underwater fog:

### software renderer (couldn't get the same exact frame captured as the other pictures sorry.): ![hl1 software renderer underwater webp](https://github.com/ValveSoftware/halflife/assets/61405538/0b9655c6-2ce6-43d9-b70c-465ec88ba811)

### `gl_use_shaders` set to `0`: ![off 70_20231119184332_1 webp](https://github.com/ValveSoftware/halflife/assets/61405538/eaaab439-7c2b-4941-98c9-6a462cb1ff2a)

### `gl_use_shaders` set to `1`: ![on 70_20231119184335_1 webp](https://github.com/ValveSoftware/halflife/assets/61405538/12ed86bf-af4e-4d84-a523-671d7443b0d5)

**Comment by megakarlach** [comment]
Better comparison after November 19 patch:

## <code>gl_use_shaders 0</code> with latest update, vanilla:
![gl_use_shaders 0 - new update](https://github.com/ValveSoftware/halflife/assets/60382442/f9d2b44a-fb4a-4309-8a03-86bfac55fa3e)

## <code>gl_use_shaders 1</code> with latest update, vanilla:
![gl_use_shaders 1 - new update](https://github.com/ValveSoftware/halflife/assets/60382442/6bacdf98-0293-419c-89b9-92716260f9ea)

## <code>gl_use_shaders 1</code> and <code>gl_overbright 0</code> with latest update, HLFixes 1.20 Beta 1:
NOTE: HLFixes 1.20 Beta 1 is only compatible with older Nov 17 version, but it works fine with the Nov 19 patch.
![gl_overbright 0 - gl_use_shaders 1 HLFixes](https://github.com/ValveSoftware/halflife/assets/60382442/b0ee9d9f-10bd-4582-8a5e-93668df9e15f)
Fogs looks extremely dark, and the brightness was reduced.

## <code>gl_use_shaders 0</code> and <code>gl_overbright 0</code> with latest update, HLFixes 1.20 Beta 1:
![gl_overbright 0 - gl_use_shaders 0 HLFixes](https://github.com/ValveSoftware/halflife/assets/60382442/ce7375c4-926d-44e2-9d05-34da0013a82a)

## <code>gl_use_shaders 0/1</code> and <code>gl_overbright 1</code> with latest update, HLFixes 1.20 Beta 1:
![gl_overbright 1 - gl_use_shaders 1 HLFixes](https://github.com/ValveSoftware/halflife/assets/60382442/861a8e42-5ef6-4aa8-a4c5-2258f3bc9e67)
If gl_overbright 1 is enabled (with HLFixes patch), gl_use_shaders does nothing.

**Comment by megakarlach** [comment]
Another comparison with <code>disposal</code> map:
## <code>gl_use_shaders 0</code> with latest update, vanilla:
![gl_use_shaders 0 vanilla](https://github.com/ValveSoftware/halflife/assets/60382442/553dcea4-34c4-4a29-acf7-41aff5c00bd6)

## <code>gl_use_shaders 1</code> with latest update, vanilla:
![gl_use_shaders 1 vanilla](https://github.com/ValveSoftware/halflife/assets/60382442/13b510cc-e639-4d28-821c-783cfe6e5245)

## <code>gl_use_shaders 1</code> and <code>gl_overbright 0</code> with latest update, [HLFixes](https://github.com/IntriguingTiles/HLFixes/releases) 1.20 Beta 1:
![gl_use_shaders 1 HLFix](https://github.com/ValveSoftware/halflife/assets/60382442/ede0b6b7-6f36-436c-9a9f-f3d0a86c6f67)
Differences: Appears to be darker than vanilla.

## <code>gl_use_shaders 0</code> and <code>gl_overbright 0</code> with latest update, HLFixes 1.20 Beta 1:
![gl_use_shaders 0 HLFix](https://github.com/ValveSoftware/halflife/assets/60382442/0818dd27-bcf5-430c-af0f-05ed544c3411)
Looks the same as having it off on vanilla, same brightness.

## <code>gl_use_shaders 0/1</code> and <code>gl_overbright 1</code> with latest update, HLFixes 1.20 Beta 1:
If gl_overbright 1 is enabled (with HLFixes patch), gl_use_shaders does nothing.
![gl_overbright 1](https://github.com/ValveSoftware/halflife/assets/60382442/1c364499-59aa-4876-bd59-b8867e3c6c35)
Differences: Waste looks much brighter with gl_use_shaders 1 on vanilla than gl_overbright 1 with HLFixes patch.

**Comment by PaHgoM** [comment]
Underwater rendered with OpenGL looks buggy, look at semitransparent wall on the screenshots. If only they could do the same look as SW renderer does

**Comment by megakarlach** [comment]
Decided to testing it again with `c2a4e.bsp` (Questionable Ethics), with HLFixes (latest one, 1.2.0 beta 2, which just come out recently) and vanilla, both seems to look identical. This time I have to make sure the `gl_overbright` and `gl_use_shaders` are loading properly by reloading the map to get the actual result.

# Questionable Ethics
## `gl_use_shaders 1`
![gl_use_shaders 1](https://github.com/ValveSoftware/halflife/assets/60382442/354238e3-ca74-4479-a1a5-9645289ce26b)
## `gl_overbright 1`
![gl_overbright 1](https://github.com/ValveSoftware/halflife/assets/60382442/08e5c0ca-f4d7-4738-95c7-fab9d56c0f21)

# Underwater bug (Surface Tension)
However, underwater bug is still present.
## `gl_overbright 1` - Underwater (HLFixes 1.2.0 B2)
![gl_overbright 1 uw](https://github.com/ValveSoftware/halflife/assets/60382442/6b61bc0a-edd6-47a2-96e7-a28b04fe4cfd)

## `gl_use_shaders 1` - Underwater (HLFixes 1.2.0 B2)
![gl_use_shaders 1 - HLFixes](https://github.com/ValveSoftware/halflife/assets/60382442/8f6e3bb6-3cc4-467f-8044-1222fd131da5)
## `gl_use_shaders 1` - Underwater (Vanilla)
![hl 2023-11-22 21-49-16](https://github.com/ValveSoftware/halflife/assets/60382442/11946cb5-5b17-4979-bc31-19568eca1dea)

# Brightness/Gamma settings
`brightness 1`
`gamma 2.2`

# Version
`Protocol version 48`
`Exe version 1.1.2.2 (valve)`
`Exe build: 23:48:06 Nov 20 2023 (9888)`

**Comment by Matthaiks** [comment]
November 22, 2023 Update

> Fixed underwater fog rendering in OpenGL.

![c2a50000](https://github.com/ValveSoftware/halflife/assets/3577122/4e523b8b-550f-4eb1-abdb-e6afb0a7504c)

**Comment by Deus-nsf** [comment]
Not bad, I wonder if the tranparent textures can be included in the fog pass.

**Comment by Maharic** [comment]
well, this most recent update seemed to have fixed the water-fog with overbright enabled, but it broke being able to enable Detailed Textures with overbright.

Detailed Textures and Overbright combined wasn't possible until the Anniversary update, but now it isn't working.

If it's possible try to get all 3 working Overbright/DT/FOG simultaneously and it will be the best it has ever been.   

Also, I think depending on the game, if Shaders are enabled by default now, it's going to break DT with no ingame option to disable the overbright/shader.  DOD/CSZ both can use DT among with mods.

**Comment by 54ac** [comment]
> Detailed Textures and Overbright combined wasn't possible until the Anniversary update, but now it isn't working.

Are you sure detail textures worked together with shaders before? I was under the impression it was one or the other, like overbright pre-Anniversary, but I haven't tested this out much. There is an unused detail textures entry in the new video options menu, hopefully we won't have to deal with a limitation from decades ago for much longer.

**Comment by jakura-nuva** [comment]
> November 22, 2023 Update
> 
> > Fixed underwater fog rendering in OpenGL.

Definitely better than before, lthough HLFixes is still viable since it preserves the correct appearance of certain models underwater (like that black gate). It would be nice if they could tweak the effect further, but at least it's been restored to its pre-anniversary state.

**Comment by Maharic** [comment]
> > Detailed Textures and Overbright combined wasn't possible until the Anniversary update, but now it isn't working.
> 
> Are you sure detail textures worked together with shaders before? I was under the impression it was one or the other, like overbright pre-Anniversary, but I haven't tested this out much. There is an unused detail textures entry in the new video options menu, hopefully we won't have to deal with a limitation from decades ago for much longer.

![20231122144511_1](https://github.com/ValveSoftware/halflife/assets/151443551/fe78b455-22a6-42ce-9880-e2cb3215e3e2)
![20231122004506_1](https://github.com/ValveSoftware/halflife/assets/151443551/e364b301-f87a-4137-bf1c-7786c7a36c58)

Yeah, it works.

I was actually in the middle of creating some new subtle Detailed Textures too haha.   Just because I was happy I could combined which wasn't possible before. 

Also, a lot of upcoming mods use a lot of DT now, even if subtle, which all looks even better combined with Overbright.

**Comment by DisrespectDwardo** [comment]
> In OpenGL, `gl_overbright` is no longer used. The new command is `gl_use_shaders` (default 1), the overbright fix is implemented on the shader level

They should remove the cvar then.

**Comment by Enokilis** [comment]
> > In OpenGL, `gl_overbright` is no longer used. The new command is `gl_use_shaders` (default 1), the overbright fix is implemented on the shader level
> 
> They should remove the cvar then.

It probably still does something if you rely on the old method (for whatever reason). Either way, they should rather make it actually do something by default.

**Comment by Enokilis** [comment]
Looks like there is a different issue.
While the world is now affected by overbright, models are still clamped at 100% in OpenGL. In software rendering, models are properly overbrigtened as well.
![overbrights](https://github.com/ValveSoftware/halflife/assets/29983795/54bde861-9077-472b-a832-0ead43f336f2)
![20231123045819_1](https://github.com/ValveSoftware/halflife/assets/29983795/c4a1756d-68a9-4a2f-84ec-4c11ead85403)

**Comment by megakarlach** [comment]
Same thing. In this new update HLFixes (both 1.2.0 Beta 1 and 2) stops working aswell (as `gl_overbright` does nothing now even it was patched using HLFixes), so had to using the pre-25th with HLFixes patch to compare the changes.
# Software renderer
![software renderer](https://github.com/ValveSoftware/halflife/assets/60382442/02c70eb5-b594-4d06-905c-eef0542fb8cf)
# `gl_use_shaders 1`
![gl_use_shaders 1 - c2a5](https://github.com/ValveSoftware/halflife/assets/60382442/7af5453c-9c48-4b7d-8b59-0fac8645c45a)
# `gl_overbright 1` (older pre-25th anniversary with HLFixes 1.1.0)
![gl_overbright 1 - pre-25 - c2a5](https://github.com/ValveSoftware/halflife/assets/60382442/af51f031-4a60-4651-a9ff-51e1e64c67ba)
# `gl_use_shaders 0`
![gl_use_shaders 0 - c2a5](https://github.com/ValveSoftware/halflife/assets/60382442/9a58b04c-0cae-4ca8-9317-6fe787ee07e1)


# Engine version (new version only)
`Protocol version 48`
`Exe version 1.1.2.2/Stdio (valve)`
`Exe build: 12:56:39 Nov 22 2023 (9890)`

**Comment by Maharic** [comment]
Currently it seems Detailed Textures, Underwater Fog, and Overbright are all working in tandem now.

**Comment by Enokilis** [comment]
The fact that there was always an inconsistency between models and the world just reinforces the need for it to be optional, for I would rather have a cohesive look than the occasional eye candy.

Really though, it should be an easy fix. There is a fragment shader in the files that controls this behavior using predefined math. All it would take was a variable inserted into the shader code based on the state of gl_overbright.
A similar fragment shader for models would also work out well. Here is Xash3D with unified overbrightness using just fixed function OpenGL 1.3. Nothing sticks out and creates the infamous cartoon object effect. https://tvtropes.org/pmwiki/pmwiki.php/Main/ConspicuouslyLightPatch
![c2a5x_shot0000](https://github.com/ValveSoftware/halflife/assets/29983795/ae3226e1-7929-4a6f-8785-6b7c3ea6097d)

**Comment by jakura-nuva** [comment]
> Currently it seems Detailed Textures, Underwater Fog, and Overbright are all working in tandem now.  
> 
> *edit*
> 
> At least with Half-Life only.  

@SirYodaJedi should be able to verify detailed textures working again in both CS and DoD per today's update - they

**Comment by Deus-nsf** [comment]
How do one get DT with Half Life? Through a mod?

**Comment by Matthaiks** [comment]
gl_use_shaders seems broken in DoD. CZero won't even launch (`Assertion failed!`).

**Comment by Enokilis** [comment]
> How do one get DT with Half Life? Through a mod?

It's a feature of GoldSrc added in Condition Zero, but it can retroactively be added with mods.
https://gamebanana.com/mods/6737

**Comment by SirYodaJedi** [comment]
> @SirYodaJedi should be able to verify detailed textures working again in both CZero and DoD per today's update - they had a separate issue for it that they marked as "completed" this morning.

> gl_use_shaders seems broken in DoD. CZero won't even launch (Assertion failed!).

I only tested in DoD, yes; haven't bothered testing CZero because I've heard it doesn't load (which is a separate issue altogether). 
You might be right about gl_use_shaders being broken in DoD; it didn't make any visible difference when toggled. I closed #3555 nonetheless because the detail textures themselves weren't broken, which was what the issue was for.

**Comment by Bittermens** [comment]
i hope they manage to fix this issue with the renderer gl_use_shaders

**Comment by Maharic** [comment]
> Looks like there is a different issue. While the world is now affected by overbright, models are still clamped at 100% in OpenGL. In software rendering, models are properly overbrigtened as well. ![overbrights](https://user-images.githubusercontent.com/29983795/285097997-54bde861-9077-472b-a832-0ead43f336f2.jpg) ![20231123045819_1](https://user-images.githubusercontent.com/29983795/285098080-c4a1756d-68a9-4a2f-84ec-4c11ead85403.jpg)

Overbright on models (aka: Overbrightbits) I don't think was ever supported in Half-life with 3D acceleration.  So that would be a new feature.

**Comment by Deus-nsf** [comment]
> > Looks like there is a different issue. While the world is now affected by overbright, models are still clamped at 100% in OpenGL. In software rendering, models are properly overbrigtened as well.
> 
> Overbright on models (aka: Overbrightbits) I don't think was ever supported in Half-life with 3D acceleration. So that would be a new feature.

It indeed wasn't, which is one of the reason I always preferred Software rendering over OpenGL, with some legacy effects like more accurate colors with tranparency and the sweet looking water ripple effect.
And I'm all in for new features :) Basically Software is the ground truth, and I want OpenGL to be like Software, but in 32 bit color and arbitrary resolutions.

**Comment by Enokilis** [comment]
The lack of 24-bpp is the only reason I stay away from software rendering. Unreal managed to do it in its software renderer.

**Comment by Maharic** [comment]
After today's hotfix, it doesn't seem that `sv_allow_shaders` is enabled by default on every application.  (Like, Team Fortress Classic) Which makes the new shader option in the menu not function.

**Comment by goodusername123** [comment]
> After today's hotfix, it doesn't seem that `sv_allow_shaders` is enabled by default on every application. (Like, Team Fortress Classic) Which makes the new shader option in the menu not function.

Yeah It seems like `sv_allow_shaders` is defaulted to off in the engine and flipped on specifically in Half-Life 1 meaning that currently the "Use shaders" option under video settings is effectively non-functional by default for any GoldSrc game that isn't Half-Life 1.

This affects and is not limited to the below:
- Half-Life: Blue Shift
- Half-Life: Opposing Force
- Team Fortress Classic
- Counter-Strike
- Counter-Strike: Condition Zero
- Counter-Strike: Condition Zero Deleted Scenes
- Day of Defeat
- Deathmatch Classic

If possible please make it so `sv_allow_shaders` is defaulted to `1` engine side or maybe find a way to hardcode the new overbright shader and have `sv_allow_shaders` just affect loading of custom non-default shaders.

**Comment by shawns-valve** [comment]
gl_use_shaders is indeed the 25th anniversary implementation of overbright support. Some issues with the originally shipped shader were fixed in patches late last year.

**Comment by Deus-nsf** [comment]
> Looks like there is a different issue. While the world is now affected by overbright, models are still clamped at 100% in OpenGL. In software rendering, models are properly overbrigtened as well. ![overbrights](https://private-user-images.githubusercontent.com/29983795/285097997-54bde861-9077-472b-a832-0ead43f336f2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwMjM0NzEsIm5iZiI6MTcyODAyMzE3MSwicGF0aCI6Ii8yOTk4Mzc5NS8yODUwOTc5OTctNTRiZGU4NjEtOTA3Ny00NzJiLWE4MzItMGVhZDQzZjMzNmYyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA0VDA2MjYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2NTEwOWM3MzE3ZDg2YzkzMTQwZTI3MTY2OTczYmE1OTI0MDJkYjU2NWM3NWY2ZDU1ODc3MGZjMWNmNGM4YzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aPUCT3_Jm_EjyhH6PJNScWm7Ex72-rorCRlQWB7gKS4) ![20231123045819_1](https://private-user-images.githubusercontent.com/29983795/285098080-c4a1756d-68a9-4a2f-84ec-4c11ead85403.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwMjM0NzEsIm5iZiI6MTcyODAyMzE3MSwicGF0aCI6Ii8yOTk4Mzc5NS8yODUwOTgwODAtYzRhMTc1NmQtNjhhOS00YTJmLTg0ZWMtNGMxMWVhZDg1NDAzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA0VDA2MjYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzZjRhMDNiYTJlZDRkMGM4Y2Q5NTcyNjIwYzAxNjk0ZjI2ZjdlYTJmMDMyODFhZjk4Y2Y3YWQxZTZjYmI2ZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2NZYrfk1Rp5ahvx10o2Hh-t-ettUtpLCSA3RL1Sqo38)

Unfortunately I just checked and this is still an issue, does it on every models, entities etc... everything that isn't static map geometry. I could just play in software but the performance tanks with transparency on the steam deck in software. Also we really need the software water in open gl...

**Comment by OpenRift412** [comment]
> Unfortunately I just checked and this is still an issue, does it on every models, entities etc... everything that isn't static map geometry. I could just play in software but the performance tanks with transparency on the steam deck in software. Also we really need the software water in open gl...

I just did a comparison between the Anniversary version and WON version 1.0.1.6 and neither of them applied overbrights to models, at least not in the same way that the software renderer does.
