### ISSUE TITLE
25th Anniversary - Menu music starts playing along with Valve intro

### ISSUE THREAD

**Issue by ThatRoboticFish** [ValveSoftware/halflife#3438]
I experienced this when running mods like Sven Co-op 3.0, BuzzyBots, Decay PC and Counter-Strike.

**Comment by WizenTV** [comment]
i have no music in my menu in my case..

**Comment by megakarlach** [comment]
> i have no music in my menu in my case..

HL1 does not actually have music in menu at all, as it's doesn't have gamestartup.mp3. If you have that file in valve/media folder, or in one of the mods (such as Sven Co-op 4.x or earlier for example), it would play.

**Comment by Individualised** [comment]
I'd like to bring up #979 as this issue is an extension of that (gamestartup playing in non-title screen scenarios). It was initially closed as fixing it would cause other issues, but given that HL25 is no longer compatible with older mods I feel like now is the time to fix this. gamestartup should only play on the titlescreen; it should not continue to play in-game or play before the titlescreen has even loaded.

**Comment by aWhhdGVteXNlbGY** [comment]
I think this has been solved because anyway I have never seen the intro again on other mods in recent updates

**Comment by sabianroberts** [comment]
It is most certainly not fixed and this issue should stay open

**Comment by aWhhdGVteXNlbGY** [comment]
i read from other issues that it's still not possible to use the video files outside of valve so this does not affect other mods and i'm not sure who will be the weirdo will use bgms on original valve folder

**Comment by sabianroberts** [comment]
This does affect mods. I am a mod developer and the issue still persists. It should remain open.
