### ISSUE TITLE
CS 1.6 and Steam crashed on linux when someone was talking in a voice chat

### ISSUE THREAD

**Issue by octopus-spore** [ValveSoftware/halflife#3898]
The game and Steam often (but not always) crashes when someone speaks into a voice chat. The sound loops and the CS 1.6 / Steam crashes.

Operating System: Manjaro Linux 
KDE Plasma Version: 6.2.5
KDE Frameworks Version: 6.10.0
Qt Version: 6.8.2
Kernel Version: 6.1.127-2-MANJARO (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i3-2350M CPU @ 2.30GHz
Memory: 7,6 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 3000

Game Version: 
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
Exe build: 01:35:13 Oct  8 2024 (10211)

Steam Beta Branch:  Stable Client
Steam Version:  1738026274
Steam Client Build Date:  Tue, Jan 28 3:50 AM UTC +03:00
Steam Web Build Date:  Tue, Jan 28 3:44 AM UTC +03:00
Steam API Version:  SteamClient021

```
crash_20250218015416_36.dmp[14271]: Uploading dump (out-of-process)
/tmp/dumps/crash_20250218015416_36.dmp
/home/anon958/.local/share/Steam/steam.sh: line 949: 13334 Segmentation fault      (core dumped) "$STEAMROOT/$STEAMEXEPATH" "$@"
    ~  crash_20250218015416_36.dmp[14271]: Finished uploading minidump (out-of-process): success = yes   ✔  7m 9s  
crash_20250218015416_36.dmp[14271]: response: CrashID=bp-8506e860-9c14-46a2-8baa-ffb572250217
crash_20250218015416_36.dmp[14271]: file ''/tmp/dumps/crash_20250218015416_36.dmp'', upload yes: ''CrashID=bp-8506e860-9c14-46a2-8baa-ffb572250217''
Error:/home/anon958/.local/share/Steam/steamapps/common/Half-Life/.so: cannot open shared object file: No such file or directory
src/common/pipes.cpp (882) : fatal stalled cross-thread pipe (pipe is disconnected).
src/common/pipes.cpp (882) : fatal stalled cross-thread pipe (pipe is disconnected).
src/common/pipes.cpp (882) : Fatal assert; application exiting
02/18 01:55:26 Init: Installing breakpad exception handler for appid(hl_linux)/version(1.0)/tid(14123)
assert_20250218015526_5.dmp[14336]: Uploading dump (out-of-process)
/tmp/dumps/assert_20250218015526_5.dmp
assert_20250218015526_5.dmp[14336]: Finished uploading minidump (out-of-process): success = yes
assert_20250218015526_5.dmp[14336]: response: Discarded=1
assert_20250218015526_5.dmp[14336]: file ''/tmp/dumps/assert_20250218015526_5.dmp'', upload yes: ''Discarded=1''
pid 14336 != 14335, skipping destruction (fork without exec?)
```

**Comment by bvfalcon** [comment]
The same error for me. But it is possible to play with turned off voice settings

**Comment by octopus-spore** [comment]
>turned off voice setting

In my case, the setting "voice_enabled 0" did not help. Maybe CS 1.6 crashes from various events, not just voice chat. I also tried: 
1) Use Steam from flatpak.
2) Use «steam_legacy» build CS 1.6.  
3) Play with the default game settings, without changing the settings. 
4) Resetting and reinstalling the Steam
5) Install OS updates. My OS has been updated now.

**Comment by jcbbb** [comment]
Same thing is happening for me, did you find a solution? I am also using KDE Plasma, maybe the issue with them?

**Comment by marstral** [comment]
The same bug/error for me.
Pop OS 22.04/Nvidia driver 565

voice_enable 0 and uncheck the box on voice settings are fixed this issue.(no voice communication)

**Comment by VSiniak12** [comment]
Hi, the same for me.  "voice_enabled 0" helps me, but maybe have more suitable fix?

**Comment by kouta-kun** [comment]
Still happening on Arch Linux. 

Attaching the /tmp/dumps files.
[cs1.6dmps.zip](https://github.com/user-attachments/files/24196362/cs1.6dmps.zip)

**Comment by Josefiks** [comment]
Same here, game and Steam client crashes. I think its related to non-steam servers when non-steam players are talking. When Steam players talk its not happening.

voice_modenable 0
voice_enabled 0

Seems to fix this issue.

**Comment by ArijanJ** [comment]
game is unplayable, any hopes of this getting picked up @kisak-valve?

**Comment by ArijanJ** [comment]
well, since it crashes with `Error:/home/anon958/.local/share/Steam/steamapps/common/Half-Life/.so: cannot open shared object file: No such file or directory`, this seems to work for me but i only tested for a few minutes:
- disable proton / compatibility layer (to use native linux build of the game)
- go to /steamapps/common/Half-Life
- copy voice_speex.co, rename the copy to ".so" (i dont know what .so it's expecting but this might work fine? i can hear other players)

**Comment by octopus-spore** [comment]
> * copy voice_speex.co, rename the copy to ".so"

Unfortunately, it didn't help. Maybe something fixed it, but the game crashed anyway.

**Comment by ArijanJ** [comment]
Yep, crashed for me now too, so that won't help :(
Looks like players who are not authenticated with steam can speak, but when another steam player talks, everything crashes and dies
edit: but no, I just joined a server and I can hear steam players - must be something else

**Comment by Mrbxx** [comment]
https://github.com/Mrbxx/ReVoiceNext

**Comment by matheusnuned** [comment]
@kisak-valve Any updates? Is Valve working to resolve this or can we assume it will never be officially fixed?

**Comment by ArijanJ** [comment]
Patch: https://github.com/makindotcc/hl-linux-voicechat-crash-fix
